config/routes.rb
Rails.application.routes.draw do
  resources    :urls, only: [:new, :create, :show]
  root         to: 'statics#home'
  get ':name', to: 'urls#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord

    validates :original, presence: true
    validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def new
    @url = Url.new
  end

  def create
    @url = Url.new(user_params)
    @url.short = url_shorten(@url)
    if @url.save
      flash[:success] = "Shorten Url Created Successfully"
      redirect_to @url.short
    else
      render 'new'
    end
  end

  def show
    url = Url.find_by(name:params[:name])
    redirect_to url.original
  end
end

private

def user_params
  params.require(:url).permit(:original, :name)
end

def url_shorten(url)
  short = root_url + url.name
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @url.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@url.errors.count, "error") %>.
    </div>
    <ul>
    <% @url.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/statics/home.html.erb
<h1>My URL Shortener Tool</h1>

<%= link_to  "New URL", new_url_path %>

app/views/urls/create.html.erb
<h1>Urls#create</h1>
<p>Find me in app/views/urls/create.html.erb</p>

app/views/urls/edit.html.erb
<h1>Urls#edit</h1>
<p>Find me in app/views/urls/edit.html.erb</p>

app/views/urls/new.html.erb
<h1>Urls#new</h1>
<p>Find me in app/views/urls/new.html.erb</p>
        <%= form_with( model: @url , local: true) do |f| %>

        <%= render 'shared/error_messages' %>

        <%= f.label :original, "URL" %>
        <%= f.text_field :original, class: "form-control" %>

        <%= f.label :name , "Custom Link" %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.submit "Create Short", class:"btn btn-primary"%>
        <% end %>

app/views/urls/show.html.erb
<h1>Urls#show</h1>
<p>Find me in app/views/urls/show.html.erb</p>

app/views/urls/update.html.erb
<h1>Urls#update</h1>
<p>Find me in app/views/urls/update.html.erb</p>